#
## /etc/zlogin and .zlogin are sourced in login shells.  It should
## contain commands that should be executed only in
## login shells.  It should be used to set the terminal
## type and run a series of external commands (fortune,
## msgs, from, etc).
##
#
export LESS='-g -i -M -R -w -z-4'

# cdrを有効化
autoload -Uz chpwd_recent_dirs cdr add-zsh-hook
add-zsh-hook chpwd chpwd_recent_dirs
zstyle ':chpwd:*' recent-dirs-max 5000
zstyle ':chpwd:*' recent-dirs-default yes
zstyle ':completion:*' recent-dirs-insert both

setopt auto_cd
function chpwd() {ls -l}

export HISTSIZE=10000
export HISTIGNORE=ls:history
export HISTTIMEFORMAT='%Y-%m-%d %T '     # bashのhistory zshのfc -ifldで使用する時刻フォーマット
export SAVEHIST=10000                    # saveする量
setopt EXTENDED_HISTORY                  # zshの開始終了を記録
setopt extended_history                  # 履歴ファイルに時刻を記録
setopt hist_ignore_dups                  # 重複を記録しない
setopt hist_reduce_blanks                # スペース排除
setopt inc_append_history                # 履歴をインクリメンタルに追加
function history-all { history -E 1 }

alias history='fc -ifld 1'
alias vi='vim'

setopt COMBINING_CHARS

autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^p" history-beginning-search-backward-end
bindkey "^n" history-beginning-search-forward-end

if [ -f "$HOME/.zsh/zaw.zsh" ]; then
  source ~/.zsh/zaw.zsh
  zstyle ':filter-select' case-insensitive yes # 絞り込みをcase-insensitiveに
  bindkey '^[' zaw-cdr
fi
